# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "rom", "~> 5.2"

gem "rom-sql", "~> 3.5"

gem "sqlite3", "~> 1.4"

gem "rom-yaml", "~> 3.0"
