name: Generate data
on:
  workflow_dispatch:
  push:
    paths:
      - untappd.json
      - .github/workflows/generator.yaml

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: robinraju/release-downloader@v1.8
        with:
          repository: "kyrremann/unparsd"
          latest: true
          fileName: "unparsd"
      - run: |
          chmod +x unparsd
          ./unparsd
      - name: Commit back
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@github.com"
          git add -A ./_data ./_monthly
          git commit -m "ci: Genereated new data" || echo "No changes to commit"
          git push
