name: Genereate data
on:
  push:
    paths:
      - untappd.json
      - parser.rb
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.x'
    - name: Install gems
      run: gem install countries
    - name: Run parser
      run: ruby parser.rb untappd.json
    - name: Commit back
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "Github Action"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git checkout master
        git add -A .
        git commit -m "Genereated new data"
        git push
